-- Migration to create missing tables for Colla Guirigall
-- Created on 2026-03-17

-- Create events table
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'Actuació',
  date TIMESTAMP WITH TIME ZONE NOT NULL,
  location TEXT,
  notes TEXT,
  isPublished BOOLEAN DEFAULT FALSE,
  createdBy TEXT,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  repertoireIds JSONB DEFAULT '[]'::jsonb
);

-- Create attendances table
CREATE TABLE IF NOT EXISTS public.attendances (
  eventId BIGINT REFERENCES public.events(id) ON DELETE CASCADE,
  userId TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pendent',
  convocat BOOLEAN DEFAULT FALSE,
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  PRIMARY KEY (eventId, userId)
);

-- Create notifications table
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  userId TEXT NOT NULL,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  read BOOLEAN DEFAULT FALSE,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  link TEXT,
  eventId BIGINT REFERENCES public.events(id) ON DELETE CASCADE
);

-- Enable RLS
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Basic policies
CREATE POLICY "Enable all for authenticated users" ON public.events FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.attendances FOR ALL TO authenticated USING (true);
CREATE POLICY "Enable all for authenticated users" ON public.notifications FOR ALL TO authenticated USING (true);
